const DefaultNode = {
	ROOT: {
		type: { resolvedName: 'ContainerWrapper' },
		isCanvas: true,
		props: {
			paddingTop: 5,
			paddingRight: 5,
			paddingBottom: 5,
			paddingLeft: 5,
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			background: '#eeeeee',
		},
		displayName: 'Container',
		custom: {},
		hidden: false,
		nodes: [],
		linkedNodes: { Container: 'ouR1DAS9a1' },
	},
	ouR1DAS9a1: {
		type: { resolvedName: 'Container' },
		isCanvas: true,
		props: {
			paddingTop: 20,
			paddingRight: 20,
			paddingBottom: 20,
			paddingLeft: 20,
			marginTop: 5,
			marginRight: 0,
			marginBottom: 5,
			marginLeft: 0,
		},
		displayName: 'Container',
		custom: {},
		parent: 'ROOT',
		hidden: false,
		nodes: ['E1__sHYAFT', 'c2MuWw-blM', 'VITXkMbvJk'],
		linkedNodes: {},
	},
	'c2MuWw-blM': {
		type: { resolvedName: 'ContainerWrapper' },
		isCanvas: false,
		props: {},
		displayName: 'Container',
		custom: {},
		parent: 'ouR1DAS9a1',
		hidden: false,
		nodes: [],
		linkedNodes: { Container: 'dS5FQ4oWFg' },
	},
	dS5FQ4oWFg: {
		type: { resolvedName: 'Container' },
		isCanvas: true,
		props: {
			paddingTop: 20,
			paddingRight: 20,
			paddingBottom: 20,
			paddingLeft: 20,
			marginTop: 5,
			marginRight: 0,
			marginBottom: 5,
			marginLeft: 0,
		},
		displayName: 'Container',
		custom: {},
		parent: 'c2MuWw-blM',
		hidden: false,
		nodes: ['cDc1fjQfq9'],
		linkedNodes: {},
	},
	E1__sHYAFT: {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: { text: 'Text', fontSize: 20 },
		displayName: 'Text',
		custom: {},
		parent: 'ouR1DAS9a1',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	cDc1fjQfq9: {
		type: { resolvedName: 'Button' },
		isCanvas: false,
		props: {
			size: 'small',
			variant: 'contained',
			color: 'primary',
			text: 'Button',
			marginTop: '0',
			marginRight: '0',
			marginBottom: '0',
			marginLeft: '0',
			paddingTop: '5',
			paddingRight: '5',
			paddingBottom: '5',
			paddingLeft: '5',
		},
		displayName: 'Button',
		custom: {},
		parent: 'dS5FQ4oWFg',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	VITXkMbvJk: {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: { text: 'Text', fontSize: 20 },
		displayName: 'Text',
		custom: {},
		parent: 'ouR1DAS9a1',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
}

export default DefaultNode
