const DefaultNode = {
	ROOT: {
		type: { resolvedName: 'Container' },
		isCanvas: true,
		props: {
			padding: 5,
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			background: '#eeeeee',
		},
		displayName: 'Container',
		custom: {},
		hidden: false,
		nodes: [],
		linkedNodes: { InnerContainer: 'iEYhiVz0LK' },
	},
	iEYhiVz0LK: {
		type: { resolvedName: 'InnerContainer' },
		isCanvas: true,
		props: {
			padding: 20,
			marginTop: 5,
			marginRight: 0,
			marginBottom: 5,
			marginLeft: 0,
			elementProps: {
				background: '#eeeeee',
				padding: 5,
				marginTop: 0,
				marginRight: 0,
				marginBottom: 0,
				marginLeft: 0,
			},
		},
		displayName: 'InnerContainer',
		custom: {},
		parent: 'ROOT',
		hidden: false,
		nodes: ['57FHVuDj_s', 'IdjmQ4_-bw', 'VBrmscGwrw', '3Ie05D9ByJ'],
		linkedNodes: {},
	},
	'3yy4hQ10tL': {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: { text: 'Title', fontSize: 20 },
		displayName: 'Text',
		custom: {},
		parent: 'xMNVRXwXf_',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	Nah360NyF4: {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: { text: 'Subtitle', fontSize: 15 },
		displayName: 'Text',
		custom: {},
		parent: 'xMNVRXwXf_',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	_tUKNay0Bk: {
		type: { resolvedName: 'Button' },
		isCanvas: false,
		props: {
			size: 'small',
			variant: 'contained',
			color: 'primary',
			text: 'Learn more',
			marginTop: '0',
			marginRight: '0',
			marginBottom: '0',
			marginLeft: '0',
			paddingTop: '5',
			paddingRight: '5',
			paddingBottom: '5',
			paddingLeft: '5',
		},
		displayName: 'Button',
		custom: {},
		parent: 'kJmi2Rfwt0',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	VBrmscGwrw: {
		type: { resolvedName: 'Button' },
		isCanvas: false,
		props: {
			size: 'small',
			variant: 'contained',
			color: 'primary',
			text: 'Button',
			marginTop: 22,
			marginRight: 0,
			marginBottom: '0',
			marginLeft: '0',
			paddingTop: 5,
			paddingRight: '5',
			paddingBottom: '5',
			paddingLeft: '5',
		},
		displayName: 'Button',
		custom: {},
		parent: 'iEYhiVz0LK',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	'3Ie05D9ByJ': {
		type: { resolvedName: 'Container' },
		isCanvas: false,
		props: {
			padding: 20,
			marginTop: 5,
			marginRight: 0,
			marginBottom: 5,
			marginLeft: 0,
		},
		displayName: 'Container',
		custom: {},
		parent: 'iEYhiVz0LK',
		hidden: false,
		nodes: [],
		linkedNodes: { InnerContainer: 'hh-TboYPWq' },
	},
	'hh-TboYPWq': {
		type: { resolvedName: 'InnerContainer' },
		isCanvas: true,
		props: {
			padding: 20,
			marginTop: 5,
			marginRight: 0,
			marginBottom: 5,
			marginLeft: 0,
			elementProps: {
				padding: 20,
				marginTop: 5,
				marginRight: 0,
				marginBottom: 5,
				marginLeft: 0,
			},
		},
		displayName: 'InnerContainer',
		custom: {},
		parent: '3Ie05D9ByJ',
		hidden: false,
		nodes: ['ya10JxA-EJ', '7D-LyS-Wd1'],
		linkedNodes: {},
	},
	'ya10JxA-EJ': {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: { text: 'Text', fontSize: 20 },
		displayName: 'Text',
		custom: {},
		parent: 'hh-TboYPWq',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	'7D-LyS-Wd1': {
		type: { resolvedName: 'Container' },
		isCanvas: false,
		props: {
			padding: 20,
			marginTop: 5,
			marginRight: 0,
			marginBottom: 5,
			marginLeft: 0,
		},
		displayName: 'Container',
		custom: {},
		parent: 'hh-TboYPWq',
		hidden: false,
		nodes: [],
		linkedNodes: { InnerContainer: 'TG7W_Q0ibo' },
	},
	TG7W_Q0ibo: {
		type: { resolvedName: 'InnerContainer' },
		isCanvas: true,
		props: {
			padding: 20,
			marginTop: 5,
			marginRight: 0,
			marginBottom: 5,
			marginLeft: 0,
			elementProps: {
				padding: 20,
				marginTop: 5,
				marginRight: 0,
				marginBottom: 5,
				marginLeft: 0,
			},
		},
		displayName: 'InnerContainer',
		custom: {},
		parent: '7D-LyS-Wd1',
		hidden: false,
		nodes: ['CW5gBpLHhq', 'y-_lOsf5zt'],
		linkedNodes: {},
	},
	CW5gBpLHhq: {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: { text: 'Text', fontSize: 20 },
		displayName: 'Text',
		custom: {},
		parent: 'TG7W_Q0ibo',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	'y-_lOsf5zt': {
		type: { resolvedName: 'Container' },
		isCanvas: false,
		props: {
			padding: 20,
			marginTop: 5,
			marginRight: 0,
			marginBottom: 5,
			marginLeft: 0,
		},
		displayName: 'Container',
		custom: {},
		parent: 'TG7W_Q0ibo',
		hidden: false,
		nodes: [],
		linkedNodes: { InnerContainer: '5F2GIrX60T' },
	},
	'5F2GIrX60T': {
		type: { resolvedName: 'InnerContainer' },
		isCanvas: true,
		props: {
			padding: 45,
			marginTop: 32,
			marginRight: 0,
			marginBottom: 5,
			marginLeft: 0,
			elementProps: {
				padding: 20,
				marginTop: 5,
				marginRight: 0,
				marginBottom: 5,
				marginLeft: 0,
			},
		},
		displayName: 'InnerContainer',
		custom: {},
		parent: 'y-_lOsf5zt',
		hidden: false,
		nodes: ['oTQESc2_fn'],
		linkedNodes: {},
	},
	oTQESc2_fn: {
		type: { resolvedName: 'Button' },
		isCanvas: false,
		props: {
			size: 'small',
			variant: 'contained',
			color: 'primary',
			text: 'Button',
			marginTop: '0',
			marginRight: '0',
			marginBottom: '0',
			marginLeft: '0',
			paddingTop: '5',
			paddingRight: '5',
			paddingBottom: '5',
			paddingLeft: '5',
		},
		displayName: 'Button',
		custom: {},
		parent: '5F2GIrX60T',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	'57FHVuDj_s': {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: { text: 'Text', fontSize: 20 },
		displayName: 'Text',
		custom: {},
		parent: 'iEYhiVz0LK',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	'IdjmQ4_-bw': {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: { text: 'Texts', fontSize: 50 },
		displayName: 'Text',
		custom: {},
		parent: 'iEYhiVz0LK',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
}

export default DefaultNode
