const DefaultNode = {
	ROOT: {
		type: { resolvedName: 'Container' },
		isCanvas: true,
		props: {
			padding: 5,
			background: '#eeeeee',
		},
		displayName: 'Container',
		custom: {},
		hidden: false,
		nodes: ['ZedaLWHSNe', 'iIni73StVj', 'feQT9eiK4w', 'On6DZ-O0kJ'],
		linkedNodes: {},
	},
	L4N8Y6GFHR: {
		type: { resolvedName: 'Card' },
		isCanvas: false,
		props: {},
		displayName: 'Card',
		custom: {},
		parent: 'ROOT',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	XMCDVgS1XY: {
		type: { resolvedName: 'Button' },
		isCanvas: false,
		props: {
			size: 'small',
			variant: 'contained',
			color: 'primary',
			text: 'Click me',
		},
		displayName: 'Button',
		custom: {},
		parent: 'ROOT',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	'9mDnU_fPKi': {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: { text: 'Hi world!', fontSize: 20 },
		displayName: 'Text',
		custom: {},
		parent: 'ROOT',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	xy67_g1jQT: {
		type: { resolvedName: 'Container' },
		isCanvas: true,
		props: {
			padding: 6,
			background: '#999999',
		},
		displayName: 'Container',
		custom: {},
		parent: 'ROOT',
		hidden: false,
		nodes: ['FKkept4v1L'],
		linkedNodes: {},
	},
	FKkept4v1L: {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: {
			text: "It's me again!",
			fontSize: 20,
			size: 'small',
		},
		displayName: 'Text',
		custom: {},
		parent: 'xy67_g1jQT',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	ZedaLWHSNe: {
		type: { resolvedName: 'Card' },
		isCanvas: false,
		props: {},
		displayName: 'Card',
		custom: {},
		parent: 'ROOT',
		hidden: false,
		nodes: [],
		linkedNodes: { text: 'bsihEDS75N', buttons: 'ktLWdDHQc1' },
	},
	iIni73StVj: {
		type: { resolvedName: 'Button' },
		isCanvas: false,
		props: {
			size: 'small',
			variant: 'contained',
			color: 'primary',
			text: 'Click me',
		},
		displayName: 'Button',
		custom: {},
		parent: 'ROOT',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	feQT9eiK4w: {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: { text: 'Hi world!', fontSize: 20 },
		displayName: 'Text',
		custom: {},
		parent: 'ROOT',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	'On6DZ-O0kJ': {
		type: { resolvedName: 'Container' },
		isCanvas: true,
		props: {
			padding: 6,
			background: '#999999',
		},
		displayName: 'Container',
		custom: {},
		parent: 'ROOT',
		hidden: false,
		nodes: ['y-gGbkY8j7'],
		linkedNodes: {},
	},
	'y-gGbkY8j7': {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: {
			text: "It's me again!",
			fontSize: 20,
			size: 'small',
		},
		displayName: 'Text',
		custom: {},
		parent: 'On6DZ-O0kJ',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	bsihEDS75N: {
		type: { resolvedName: 'CardTop' },
		isCanvas: true,
		props: {},
		displayName: 'CardTop',
		custom: {},
		parent: 'ZedaLWHSNe',
		hidden: false,
		nodes: ['l7WejYRVBc', '9IKo4pdv0r'],
		linkedNodes: {},
	},
	l7WejYRVBc: {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: { text: 'Title', fontSize: 20 },
		displayName: 'Text',
		custom: {},
		parent: 'bsihEDS75N',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	'9IKo4pdv0r': {
		type: { resolvedName: 'Text' },
		isCanvas: false,
		props: { text: 'Subtitle', fontSize: 15 },
		displayName: 'Text',
		custom: {},
		parent: 'bsihEDS75N',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
	ktLWdDHQc1: {
		type: { resolvedName: 'CardBottom' },
		isCanvas: true,
		props: {},
		displayName: 'CardBottom',
		custom: {},
		parent: 'ZedaLWHSNe',
		hidden: false,
		nodes: ['A_bE2dGVb0'],
		linkedNodes: {},
	},
	A_bE2dGVb0: {
		type: { resolvedName: 'Button' },
		isCanvas: false,
		props: {
			size: 'small',
			variant: 'contained',
			color: 'primary',
			text: 'Learn more',
		},
		displayName: 'Button',
		custom: {},
		parent: 'ktLWdDHQc1',
		hidden: false,
		nodes: [],
		linkedNodes: {},
	},
}

export default DefaultNode
